In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [4]:
text = ['This is a line',
           "This is another line",
       "Completely different line"]

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer,CountVectorizer

In [38]:
cv = CountVectorizer()

In [39]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [40]:
sparse_mat = cv.fit_transform(text)

In [41]:
sparse_mat.todense()         # one row--> full vocabalory 

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [42]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [43]:
cv = CountVectorizer(stop_words='english')

In [44]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [45]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [46]:
#TfidfTransformer

In [47]:
tfidf_transformer = TfidfTransformer()

In [48]:
cv = CountVectorizer()

In [49]:
counts = cv.fit_transform(text)

In [50]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [53]:
counts.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [51]:
tfidf = tfidf_transformer.fit_transform(counts)

In [52]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [ ]:
# Pipeline

In [20]:
from sklearn.pipeline import Pipeline

In [21]:
pipe = Pipeline([('cv',CountVectorizer()),('tfidf',TfidfTransformer())])

In [22]:
results = pipe.fit_transform(text)

In [23]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [24]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [25]:
#TfIdfVectorizer --> Does both above in single step

In [26]:
tfidf = TfidfVectorizer()

In [27]:
new = tfidf.fit_transform(text)

In [28]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [2]:
'''
Part-of-speech (POS) tagging is a popular Natural Language Processing process
which refers to categorizing words in a text (corpus) in correspondence with a particular part of speech, 
depending on the definition of the word and its context.
'''

'\nPart-of-speech (POS) tagging is a popular Natural Language Processing process\nwhich refers to categorizing words in a text (corpus) in correspondence with a particular part of speech, \ndepending on the definition of the word and its context.\n'

In [1]:
'''import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
stop_words = set(stopwords.words('english'))
'''


"import nltk\nfrom nltk.corpus import stopwords\nfrom nltk.tokenize import word_tokenize, sent_tokenize\nstop_words = set(stopwords.words('english'))\n"

In [ ]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
